name: bartaz-snap-build-test
version: 1.8.0
summary: This is just a test based on speed-test-snap...
description: This is just a test description

confinement: classic

apps:
  speed-test:
    command: speed-test
    plugs: [network-bind]

parts:
  speed-test:
    plugin: nodejs
    node-packages: [speed-test@1.8.0]
